In [60]:
import math
import numpy as np
import pandas as pd
import pandas as pd

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [61]:
matrix = np.arange(0, 10, 1)

In [62]:
matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
matrix[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [64]:
matrix_diagonal = np.diag(np.arange(8), k = 0)

In [65]:
matrix_diagonal

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

In [66]:
diag = []
for i in range(0, len(matrix_diagonal)):
    diag.append(matrix_diagonal[i][i])
print(sum(diag))

28


Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.

In [67]:
data_ratings = pd.read_csv('ratings.csv') 

In [68]:
data_ratings.head()

userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [69]:
data_names = pd.read_csv('movies.csv') 

In [70]:
data_names.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [83]:
data_all = pd.merge(data_names, data_ratings) #мерджим таблички

In [85]:
data_all = data_all[(data_all['rating'] == 5.0)] #сортируем, чтобы в рейтинге остались лишь пятерки

In [88]:
data_all.groupby(['title'], as_index=False).sum().sort_values(by='rating', ascending=False).head() #топ5

title   movieId      userId  \
11455           Shawshank Redemption, The (1994)  10142928  2196841751   
10340                        Pulp Fiction (1994)   8217552  1925909650   
11582           Silence of the Lambs, The (1991)  13350209  1555860513   
11200                    Schindler's List (1993)  11781085  1544120275   
12085  Star Wars: Episode IV - A New Hope (1977)   5750420  1530065554   

         rating       timestamp  
11455  159480.0  33274031442751  
10340  138810.0  28494705865090  
11582  112565.0  22199822134108  
11200  111775.0  22324051880490  
12085  110585.0  22652131996860

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 
за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.



In [245]:
data_pribalt = pd.read_csv('power.csv') 

In [246]:
data_pribalt.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [247]:
data_pribalt = data_pribalt[(data_pribalt['year'] >= 2005) & (data_pribalt['year'] <= 2010)]

In [248]:
data_pribalt = data_pribalt[(data_pribalt['quantity'] >= 0)]

In [249]:
data_pribalt = data_pribalt[(data_pribalt['category'] == 4) | (data_pribalt['category'] == 12) | (data_pribalt['category'] == 21)]

In [250]:
data_pribalt = data_pribalt[(data_pribalt['country'] == 'Lithuania') | (data_pribalt['country'] == 'Estonia') |(data_pribalt['country'] == 'Latvia')]

In [251]:
data_pribalt.head(10) #проверим

country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11157  Lithuania  2007       0.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4
12755    Estonia  2008       1.0         4
12756    Estonia  2007       0.0         4

In [254]:
data_pribalt.groupby(['country']).sum()

year  quantity  category
country                              
Estonia    198714   63440.0      1620
Latvia     184710   54844.0      1728
Lithuania  435667  122296.0      3330

In [256]:
data_quantity = data_pribalt.groupby(['country']).sum()

In [261]:
data_quantity.sort_values(by='quantity', ascending=False)

year  quantity  category
country                              
Lithuania  435667  122296.0      3330
Estonia    198714   63440.0      1620
Latvia     184710   54844.0      1728

In [262]:
data_quantity['quantity']

country
Estonia       63440.0
Latvia        54844.0
Lithuania    122296.0
Name: quantity, dtype: float64

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [263]:
from numpy import linalg